from django.urls import path
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register(r'pacientes', views.PacienteViewSet)
router.register(r'departamentos', views.DepartamentoViewSet)
router.register(r'funcionarios', views.FuncionarioViewSet)
router.register(r'consultas', views.ConsultaViewSet)
router.register(r'pagamentos', views.PagamentoViewSet)
router.register(r'exames_medicos', views.ExameMedicoViewSet)
router.register(r'equipamentos', views.EquipamentoViewSet)
router.register(r'faturas', views.FaturaViewSet)
router.register(r'consumiveis', views.ConsumivelViewSet)
router.register(r'seguradoras', views.SeguradoraViewSet)
router.register(r'procedimentos_medicos', views.ProcedimentoMedicoViewSet)
router.register(r'agendamentos', views.AgendamentoViewSet)
router.register(r'detalhes_funcionarios', views.DetalheFuncionarioViewSet)
router.register(r'detalhes_pacientes', views.DetalhePacienteViewSet)
router.register(r'receitas_medicas', views.ReceitaMedicaViewSet)
router.register(r'registros_internacao', views.RegistroInternacaoViewSet)
router.register(r'historico_consultas', views.HistoricoConsultaViewSet)
router.register(r'procedimentos_cirurgicos', views.ProcedimentoCirurgicoViewSet)
router.register(r'registros_vacinacao', views.RegistroVacinacaoViewSet)
router.register(r'testes_laboratoriais', views.TesteLaboratorialViewSet)
router.register(r'alergias_condicoes', views.AlergiaCondicaoViewSet)
router.register(r'historico_pagamentos', views.HistoricoPagamentoViewSet)
router.register(r'contatos_emergencia', views.ContatoEmergenciaViewSet)
router.register(r'especialidades_medicas', views.EspecialidadeMedicaViewSet)

urlpatterns = [
    path('', views.index, name="index"),
    path('status/', views.status_root, name='status_root'),
    path('fatura/', views.fatura_list, name='fatura_list'),
    path('fatura/<int:fatura_id>/', views.fatura_detail, name='fatura_detail'),
    path('fatura/create/', views.fatura_create, name='fatura_create'),
    path('fatura/update/<int:fatura_id>/', views.fatura_update, name='fatura_update'),
    path('fatura/delete/<int:fatura_id>/', views.fatura_delete, name='fatura_delete'),
    path('consumivel/', views.consumivel_list, name='consumivel_list'),
    path('consumivel/<int:consumivel_id>/', views.consumivel_detail, name='consumivel_detail'),
    path('consumivel/create/', views.consumivel_create, name='consumivel_create'),
    path('consumivel/update/<int:consumivel_id>/', views.consumivel_update,
         name='consumivel_update'),
    path('consumivel/delete/<int:consumivel_id>/', views.consumivel_delete,
         name='consumivel_delete'),
    path('consulta/', views.consulta_list, name='consulta_list'),
    path('consulta/<int:consulta_id>/', views.consulta_detail, name='consulta_detail'),
    path('consulta/create/', views.consulta_create, name='consulta_create'),
    path('consulta/update/<int:consulta_id>/', views.consulta_update, name='consulta_update'),
    path('consulta/delete/<int:consulta_id>/', views.consulta_delete, name='consulta_delete'),
    path('paciente/', views.paciente_list, name='paciente_list'),
    path('paciente/<int:paciente_id>/', views.paciente_detail, name='paciente_detail'),
    path('paciente/create/', views.paciente_create, name='paciente_create'),
    path('paciente/update/<int:paciente_id>/', views.paciente_update, name='paciente_update'),
    path('paciente/delete/<int:paciente_id>/', views.paciente_delete, name='paciente_delete'),
    path('pagamento/', views.pagamento_list, name='pagamento_list'),
    path('pagamento/<int:pagamento_id>/', views.pagamento_detail, name='pagamento_detail'),
    path('pagamento/create/', views.pagamento_create, name='pagamento_create'),
    path('pagamento/update/<int:pagamento_id>/', views.pagamento_update, name='pagamento_update'),
    path('pagamento/delete/<int:pagamento_id>/', views.pagamento_delete, name='pagamento_delete'),
    path('exame_medico/', views.exame_medico_list, name='exame_medico_list'),
    path('exame_medico/<int:exame_medico_id>/', views.exame_medico_detail,
         name='exame_medico_detail'),
    path('exame_medico/create/', views.exame_medico_create, name='exame_medico_create'),
    path('exame_medico/update/<int:exame_medico_id>/', views.exame_medico_update,
         name='exame_medico_update'),
    path('exame_medico/delete/<int:exame_medico_id>/', views.exame_medico_delete,
         name='exame_medico_delete'),
    path('seguradora/', views.seguradora_list, name='seguradora_list'),
    path('seguradora/<int:seguradora_id>/', views.seguradora_detail, name='seguradora_detail'),
    path('seguradora/create/', views.seguradora_create, name='seguradora_create'),
    path('seguradora/update/<int:seguradora_id>/', views.seguradora_update,
         name='seguradora_update'),
    path('seguradora/delete/<int:seguradora_id>/', views.seguradora_delete,
         name='seguradora_delete'),
    path('procedimento/', views.procedimento_list, name='procedimento_list'),
    path('procedimento/<int:procedimento_id>/', views.procedimento_detail,
         name='procedimento_detail'),
    path('procedimento/create/', views.procedimento_create, name='procedimento_create'),
    path('procedimento/update/<int:procedimento_id>/', views.procedimento_update,
         name='procedimento_update'),
    path('procedimento/delete/<int:procedimento_id>/', views.procedimento_delete,
         name='procedimento_delete'),
    path('agendamento/', views.agendamento_list, name='agendamento_list'),
    path('agendamento/<int:agendamento_id>/', views.agendamento_detail, name='agendamento_detail'),
    path('agendamento/create/', views.agendamento_create, name='agendamento_create'),
    path('agendamento/update/<int:agendamento_id>/', views.agendamento_update,
         name='agendamento_update'),
    path('agendamento/delete/<int:agendamento_id>/', views.agendamento_delete,
         name='agendamento_delete'),
    path('detalhe_funcionario/', views.detalhe_funcionario_list, name='detalhe_funcionario_list'),
    path('detalhe_funcionario/<int:detalhe_funcionario_id>/', views.detalhe_funcionario_detail,
         name='detalhe_funcionario_detail'),
    path('detalhe_funcionario/create/', views.detalhe_funcionario_create,
         name='detalhe_funcionario_create'),
    path('detalhe_funcionario/update/<int:detalhe_funcionario_id>/',
         views.detalhe_funcionario_update, name='detalhe_funcionario_update'),
    path('detalhe_funcionario/delete/<int:detalhe_funcionario_id>/',
         views.detalhe_funcionario_delete,
         name='detalhe_funcionario_delete'),
    path('detalhe_paciente/', views.detalhe_paciente_list, name='detalhe_paciente_list'),
    path('detalhe_paciente/<int:detalhe_paciente_id>/', views.detalhe_paciente_detail,
         name='detalhe_paciente_detail'),
    path('detalhe_paciente/create/', views.detalhe_paciente_create, name='detalhe_paciente_create'),
    path('detalhe_paciente/update/<int:detalhe_paciente_id>/', views.detalhe_paciente_update,
         name='detalhe_paciente_update'),
    path('detalhe_paciente/delete/<int:detalhe_paciente_id>/', views.detalhe_paciente_delete,
         name='detalhe_paciente_delete'),
    path('receita_medica/', views.receita_medica_list, name='receita_medica_list'),
    path('receita_medica/<int:receita_medica_id>/',
         views.receita_medica_detail, name='receita_medica_detail'),
    path('receita_medica/create/', views.receita_medica_create, name='receita_medica_create'),
    path('receita_medica/update/<int:receita_medica_id>/', views.receita_medica_update,
         name='receita_medica_update'),
    path('receita_medica/delete/<int:receita_medica_id>/', views.receita_medica_delete,
         name='receita_medica_delete'),
    path('registro_internacao/', views.registro_internacao_list, name='registro_internacao_list'),
    path('registro_internacao/<int:registro_internacao_id>/', views.registro_internacao_detail,
         name='registro_internacao_detail'),
    path('registro_internacao/create/', views.registro_internacao_create,
         name='registro_internacao_create'),
    path('registro_internacao/update/<int:registro_internacao_id>/',
         views.registro_internacao_update,
         name='registro_internacao_update'),
    path('registro_internacao/delete/<int:registro_internacao_id>/',
         views.registro_internacao_delete,
         name='registro_internacao_delete'),
    path('historico_consulta/', views.historico_consulta_list, name='historico_consulta_list'),
    path('historico_consulta/<int:historico_consulta_id>/', views.historico_consulta_detail,
         name='historico_consulta_detail'),
    path('historico_consulta/create/', views.historico_consulta_create,
         name='historico_consulta_create'),
    path('historico_consulta/update/<int:historico_consulta_id>/', views.historico_consulta_update,
         name='historico_consulta_update'),
    path('historico_consulta/delete/<int:historico_consulta_id>/', views.historico_consulta_delete,
         name='historico_consulta_delete'),
    path('procedimento_cirurgico/', views.procedimento_cirurgico_list,
         name='procedimento_cirurgico_list'),
    path('procedimento_cirurgico/<int:procedimento_cirurgico_id>/',
         views.procedimento_cirurgico_detail, name='procedimento_cirurgico_detail'),
    path('procedimento_cirurgico/create/', views.procedimento_cirurgico_create,
         name='procedimento_cirurgico_create'),
    path('procedimento_cirurgico/update/<int:procedimento_cirurgico_id>/',
         views.procedimento_cirurgico_update,
         name='procedimento_cirurgico_update'),
    path('procedimento_cirurgico/delete/<int:procedimento_cirurgico_id>/',
         views.procedimento_cirurgico_delete, name='procedimento_cirurgico_delete'),
    path('registro_vacinacao/', views.registro_vacinacao_list, name='registro_vacinacao_list'),
    path('registro_vacinacao/<int:registro_vacinacao_id>/', views.registro_vacinacao_detail,
         name='registro_vacinacao_detail'),
    path('registro_vacinacao/create/', views.registro_vacinacao_create,
         name='registro_vacinacao_create'),
    path('registro_vacinacao/update/<int:registro_vacinacao_id>/', views.registro_vacinacao_update,
         name='registro_vacinacao_update'),
    path('registro_vacinacao/delete/<int:registro_vacinacao_id>/', views.registro_vacinacao_delete,
         name='registro_vacinacao_delete'),
    path('teste_laboratorial/', views.teste_laboratorial_list, name='teste_laboratorial_list'),
    path('teste_laboratorial/<int:teste_laboratorial_id>/', views.teste_laboratorial_detail,
         name='teste_laboratorial_detail'),
    path('teste_laboratorial/create/', views.teste_laboratorial_create,
         name='teste_laboratorial_create'),
    path('teste_laboratorial/update/<int:teste_laboratorial_id>/',
         views.teste_laboratorial_update, name='teste_laboratorial_update'),
    path('teste_laboratorial/delete/<int:teste_laboratorial_id>/', views.teste_laboratorial_delete,
         name='teste_laboratorial_delete'),
    path('alergia_condicao/', views.alergia_condicao_list, name='alergia_condicao_list'),
    path('alergia_condicao/<int:alergia_condicao_id>/', views.alergia_condicao_detail,
         name='alergia_condicao_detail'),
    path('alergia_condicao/create/', views.alergia_condicao_create, name='alergia_condicao_create'),
    path('alergia_condicao/update/<int:alergia_condicao_id>/', views.alergia_condicao_update,
         name='alergia_condicao_update'),
    path('alergia_condicao/delete/<int:alergia_condicao_id>/', views.alergia_condicao_delete,
         name='alergia_condicao_delete'),
]
